### ISSUE TITLE
Can't move around or do anything

### ISSUE THREAD

**Issue by thenoncoder** [NagyD/SDLPoP#104]
Neither the arrows keys nor the WASD keys do anything. Or did you set different default controls?

**Comment by Falcury** [comment]
Do you have a controller plugged in by any chance? In that case joystick mode would be enabled at launch, and you could switch back to keyboard mode using Ctrl+K.

**Comment by thenoncoder** [comment]
No, just keyboard and mouse.

**Comment by zaps166** [comment]
Sometimes SDL2 can detect [Touchpad as a joystick](https://github.com/zaps166/NFSIISE/commit/d87d09b7db5a70512b42f3289586007e53c50e5d).

**Comment by thenoncoder** [comment]
I see. It didn't seem to work with a normal mouse, though, nor a keyboard.

**Comment by NagyD** [comment]
So, do the arrow keys work after you press Ctrl+K?

**Comment by thenoncoder** [comment]
Yeah. My fault for forgetting this! :D

**Comment by NagyD** [comment]
Maybe I should add an option to SDLPoP.ini that can disable automatic joystick mode at startup?
Ctrl+J would still switch to that mode, of course.

**Comment by Falcury** [comment]
Or, some way to automatically switch if you start using the other input method?
I.e. the other input method would also be polled, but that input would usually be discarded unless it's detected that the input method should be switched.

**Comment by NagyD** [comment]
> Or, some way to automatically switch if you start using the other input method?

Now, that's even better.
Autodetection is usually better than manual configuration.
I'll try that today.

**Comment by NagyD** [comment]
> Or, some way to automatically switch if you start using the other input method?

Here is my first attempt on a new branch: https://github.com/NagyD/SDLPoP/commits/auto_input_mode
I'd like you to test it because I don't have a gamepad or a joystick.

**Comment by Falcury** [comment]
OK! That's nice!
I just tested it with the Xbox 360 controller. The autodetection works! Some quirks:
* It doesn't yet work from the title screen. The current behaviour is: when starting in joystick mode, pressing shift does not start the game. Other keys can still start the game, however, keyboard mode can only become enabled while in-game.
* The input from the controller is very sensitive to accidental input. So when I would pick up the controller and put it down again, or lightly touch the analog stick, joystick input would already be registered, which switches the controls. (The fix would be to check that the input is not within the 'dead zone' of the controller.)
