### ISSUE TITLE
Some things are not cleared on screen (SDL 2.0.5)

### ISSUE THREAD

**Issue by zaps166** [NagyD/SDLPoP#105]
I've noticed some bugs using SDL 2.0.5:
- lives of defeated enemy (blue triangles at bottom-right corner),
- potion red dots.

![sdlpop_gif](https://cloud.githubusercontent.com/assets/6239090/21318503/bb882f34-c609-11e6-8f8c-5be32b0347dc.gif)

I don't know if it is an SDL 2.0.5 critical bug or the game requires simple fix because of changes in library.

**Comment by zaps166** [comment]
Possible fix: #107

**Comment by NagyD** [comment]
#107 fixes these (and opening gates as well).
