### ISSUE TITLE
replay out-of-sync

### ISSUE THREAD

**Issue by EndeavourAccuracy** [NagyD/SDLPoP#111]
Both ZIP files include video recordings of my original playing, and SDLPoP's replay files:
http://www.popot.org/Falcury.zip
http://www.popot.org/Falcury2.zip

Also, here's a comparison video of the latter:
http://www.popot.org/Falcury.webm

Download the comparison video, load it with VLC, pause the video, and then manually use the slider.
The problem occurs when changing screens.

**Comment by NagyD** [comment]
This was hopefully fixed in #112, more precisely in 6b0d75a761d522018e1a0a070a83f8dc6d4b717b.
Can I close this?

**Comment by Falcury** [comment]
This commit (https://github.com/NagyD/SDLPoP/pull/120/commits/fea24f4d185b8b022e0dac695b3d0976c7fce90c)  should fix replays going out of sync after completing a level. 
Hopefully it is now possible to record full playthroughs in a single replay, without issues.

> Can I close this?

Yes, I think so! :)
