### ISSUE TITLE
Use Unicode/UTF-8 for file paths on Windows

### ISSUE THREAD

**Issue by NagyD** [NagyD/SDLPoP#134]
Hello everyone,

I am currently working on using Unicode/UTF-8 for file paths on Windows.
This is needed so that the replay files can be opened from the command line (or with filetype association), even if the path (of either the replay or SDLPoP) contains non-ASCII characters.

This is what I have now: https://github.com/NagyD/SDLPoP/tree/UTF-8

I would like it to work in all compilers. So if you can compile for Windows, please test whether it works for you.

Thank you.

**Comment by Falcury** [comment]
I just tested it using Visual Studio 2017, and MinGW (in both cases, 32-bit). It worked as expected: I can now open and cycle through replay files that have unicode symbols in the filename. (Nice!)

**Comment by NagyD** [comment]
Good.

What about 64-bit?
[Here](https://github.com/NagyD/SDLPoP/blob/master/src/replay.c#L28), only _WIN32 is checked.
Shouldn't it also check _WIN64?

**Comment by Rondom** [comment]
`_WIN32` means the Win32-API and is defined no matter the architecture.

**Comment by NagyD** [comment]
It seems you're right.
For the Microsoft C compiler it's documented here: https://msdn.microsoft.com/en-us/library/b0084kay.aspx
For gcc, I couldn't find any concrete documentation [(see here)](https://gcc.gnu.org/onlinedocs/gcc-7.2.0/cpp/System-specific-Predefined-Macros.html), but this command line shows that `_WIN32` is defined: `cpp -dM -m64 nul | sort`
