### ISSUE TITLE
SDL_Joystick support gone, bring it back?

### ISSUE THREAD

**Issue by vanfanel** [NagyD/SDLPoP#140]
Hi there,

It seems SDLPoP left the SDL_Joystick interface in favor of the SDL_GameController interface, and I didn't notice until today.
My PSX gamepad with USB adaptor does not work anymore due to this, SDL_GameController is OK for things like the M$ gamepad, but not for USB joysticks I guess.
Now, my PSX gamepad works with any other SDL2 game, except SDLPoP :(
In fact, SDL_IsGameController() returns "false" for all the USB joysticks I have around...
So, any chances to see SDL_Joystick interface as a fallback if SDL_GameController is not detected?
It's an easy fix on set_joy_mode(), a matter of adding a new SDL_Joystick * in data.h and, well, bringing back the movement detection code again.

Thanks!

**Comment by vanfanel** [comment]
I have done a PR fixing this, since I wanted SDLPoP joystick support working again with my wired pads:
https://github.com/NagyD/SDLPoP/pull/141

**Comment by NagyD** [comment]
I have merged your PR, so I guess I can close this?

**Comment by vanfanel** [comment]
Yes, no problem on closing it. Thanks! :)
