### ISSUE TITLE
[Optimization] Moving Mix_LoadWAV_RW() call to load_sound()?

### ISSUE THREAD

**Issue by vanfanel** [NagyD/SDLPoP#142]
Hi,

Currently, Mix_LoadWAV_RW() is called every time a sound is played in play_digi_sound().
This function takes too long to return, so there are pauses during the game (it's easy to see the kid is frozen in the air when he's thrown into the dungeon at level 1 start due to this), which dissapear if this is commented out.
I think Mix_LoadWAV_RW() should be moved to load_sound(), so the conversion is done **when the sound is loaded** (during level loading) instead of being done **when the sound is played**: that would be the correct approach and gameplay would be more fluid on slow platforms.

I have done a similar experiment on the stvb branch, and it works very well (avoiding the SDL_BuildAudioCVT() call when a sound is being played, just calling it a single time in digi_init() instead).

Just to clarify, the problem on both the master and stvb branches is the SDL_BuildAudioCVT() function, which is called directly on the stvb branch (and hence can be moved to init_digi()) and is called indirectly by  Mix_LoadWAV_RW() on the master branch. Since using Mix_LoadWAV_RW() is atomic, there's no way to move the "internal" SDL_BuildAudioCVT() call that Mix_LoadWAV_RW() does to init_digi() on the master branch, so Mix_LoadWAV_RW() should be called on load_sound() instead.

**Comment by NagyD** [comment]
Here is my change on a separate branch: 3eea258559fdbed658514fdcfe368a6d834453e9
Please try it.

Is it really `SDL_BuildAudioCVT()` and not `SDL_ConvertAudio()` that takes so long?

**Comment by vanfanel** [comment]
@NagyD : The new branch works PERFECTLY, that's the way to do it! :+1: 
And yes, it's SDL_BuildAudioCVT() what takes so long.
You can safaly use this pre-convert way on the main branch. It's smooth as silk, as it should be.

**Comment by NagyD** [comment]
> You can safely use this pre-convert way on the main branch.

Okay, merged it.

> And yes, it's SDL_BuildAudioCVT() what takes so long.

Maybe you could report it at https://bugzilla.libsdl.org/, together with a testcase that measures the time of both `SDL_BuildAudioCVT()` and `SDL_ConvertAudio()` separately, or something like that.
