### ISSUE TITLE
Alt+Tabbing Back Stops Replay

### ISSUE THREAD

**Issue by EndeavourAccuracy** [NagyD/SDLPoP#157]
As mentioned [here](http://forum.princed.org/viewtopic.php?p=20031#p20031), when playing back a recording, Alt+Tabbing back to SDLPoP stops the replay if Alt is released before Tab. (Tested with Linux Mint; Xfce.)

**Comment by NagyD** [comment]
Maybe SDLPoP should ignore the tab key for some time after its window gets focus?

**Comment by EndeavourAccuracy** [comment]
I barely know the code, so this is just a shot in the dark, but can't it check whether event.type is SDL_KEYDOWN or something similar?

**Comment by NagyD** [comment]
> can't it check whether event.type is SDL_KEYDOWN or something similar?

The code is already doing that: Keyboard commands are read from the `last_key_scancode` variable, which is set only in `SDL_KEYDOWN` events.
See here: https://github.com/NagyD/SDLPoP/blob/master/src/seg009.c#L2867
(You can add a debug printout there to see what happens.)

The operating system (or SDL) automatically sends repeated keydown events if a key is held down.
For example, if I Alt+Tab into a text editor, then holding Tab down will enter tabs until I release it.
A difference between operating systems is that on Windows, there is a noticeable delay before the first repeat; but on Linux, there is no such delay.

**Comment by NagyD** [comment]
[You said that the fix works](http://forum.princed.org/viewtopic.php?p=23003#p23003), so I'm closing this.
