### ISSUE TITLE
Option to ignore .pal files and use full color

### ISSUE THREAD

**Issue by EndeavourAccuracy** [NagyD/SDLPoP#169]
A feature request.
It would be nice if there were an option to ignore .pal files, to allow the use of full-color .png files.
I'd probably make sense to turn this on by default, to give modders the most freedom out-of-the-box.
If necessary, I'd be willing to help convert all indexed .png files to full-color .png files.

**Comment by NagyD** [comment]
You can already use full-color (RGB) PNG files.
(Well, at least it works for me. Please try it and tell me the result.)

The colors in *.pal files are used only when the game directly uses a single color, such as when drawing the palace wall patterns.

And then there are the guard images/palettes. How do you plan to convert those to RGB?

**Comment by EndeavourAccuracy** [comment]
> You can already use full-color (RGB) PNG files.

That's what I thought, but @Falcury wrote [here](http://forum.princed.org/viewtopic.php?p=22946#p22946), emphasis mine:

> From a technical standpoint, though, I guess the spritesheet **would still need to be palettized, just like SDLPoP's png images are**.

I guess maybe I misunderstood him; I also replied with "Is that necessary?".
Maybe Falcury can chime in...

**Comment by Falcury** [comment]
I think I was mostly referring to the guard images (like David mentionened) and also the PRINCE.DAT palettes in 1.3/1.4 that allow the color scheme to be changed depending on the level. I haven't actually tested it, but my guess is that those things stop working. Yeah, other than that, I suppose using full RGB images would be fine, like David also confirmed above.

**Comment by EndeavourAccuracy** [comment]
I guess there's no need for this issue/ticket then.
Closing it.
