### ISSUE TITLE
SDLPoP cannot be built with gcc 10

### ISSUE THREAD

**Issue by musuruan** [NagyD/SDLPoP#204]
gcc 10 recently changed the default behaviour from -fcommon to -fno-common:
https://wiki.gentoo.org/wiki/Gcc_10_porting_notes/fno_common

With this change it is not possible to build SDPPoP:
http://koji.rpmfusion.org/kojifiles/work/tasks/8075/408075/build.log

**Comment by NagyD** [comment]
I've recently merged a pull request (#203) which fixes a similar problem with clang.
Can you check if it solves the problem for you as well?

**Comment by musuruan** [comment]
Yes, it works. Thank you very much!
