### ISSUE TITLE
Colored torches do not get restored on quick load if you restart the game

### ISSUE THREAD

**Issue by dstarosta** [NagyD/SDLPoP#220]
If you quick save a game in a level with 1 or more colored torches then restart the game. Go to level 1, assuming it has regular orange torches and click F9. The quick loaded level is going to have orange torches in place of the colored ones.

Sometimes if you quick saved to a torch, only that torch is going to change the color while the rest remain orange.

**Comment by NagyD** [comment]
I made a fix, can you test if it works for you?

**Comment by dstarosta** [comment]
In my mod I had changed the logic to be able to define torch color for each level so I cannot easily test the original scenario with custom level palettes.

But I cannot reproduce it on regular levels in the latest SDLPoP code so it is most likely fixed.
