### ISSUE TITLE
Kid can try to fight mouse after a quick load

### ISSUE THREAD

**Issue by dstarosta** [NagyD/SDLPoP#230]
The logic in the `check_can_guard_see_kid()` function below does not set `can_guard_see_kid` variable to 0. 

https://github.com/NagyD/SDLPoP/blob/16d1336d9381aa3b8d1daad308dba667e16eae0f/src/seg003.c#L632-L634

This is typically not an issue on the original level 8 because kid never stands next to mouse. Also, at that point all guards are dead.

However, if you have a custom level where you do a quick save near mouse and then quick load (later) while fighting a guard, kid will appear with his sword drawn and can even kill it. The reason is the `can_guard_see_kid` variable is not being quick saved and retains the old value.

I think instead of having separate `if` statement for mouse, the `if` statement on line 635 should include `&& Guard.charid != charid_24_mouse`.

**Comment by NagyD** [comment]
Here is my fix: db9068aeefa4bf0b37ab5283ffd11ada4e148bfd
