### ISSUE TITLE
Graphical glitch when Shadow drinks a potion

### ISSUE THREAD

**Issue by Sturwandan** [NagyD/SDLPoP#254]
I was able to make a graphical glitch. Steps to reproduce:

0. Go to the level where the shadow drinks big health potion (5th?)
1. Jump through second chomper to land between gate opening buttons. (or load attached file after unpacking and rename it to QUICKSAVE.SAV)
2. Jump up and run through the shadow, leaving the room before the shadow finished drinking the potion. Use running jump to leave in time.
3. Go back and watch

The shadow runs to the opposite side from normal (see screenshot 1) and goes through a wall, leaving a small black rectangle (see screenshot 2) behind.
[prince_shadow_drinks.sav.gz](https://github.com/NagyD/SDLPoP/files/7315314/prince2_drinks.sav.gz)

Screenshot 1:
![screenshot 1](https://user-images.githubusercontent.com/64779686/136688356-fa6f6386-afe2-4356-b947-492626f929a2.png)
Screenshot 2:
![screenshot 2](https://user-images.githubusercontent.com/64779686/136688360-0bae2673-1895-411f-ba45-64dc73eed936.png)

I do not know whenever it exists in DOS version or it's specific to SDLPoP though.

**Comment by NagyD** [comment]
Fixed: 67016451b8a3b69237708168c76b5067d443f408
