### ISSUE TITLE
Input inprecision or lag

### ISSUE THREAD

**Issue by paines** [NagyD/SDLPoP#259]
First of all: thanks a bunch for this. The dissambly job and putting this alltogether to work natively on modern hardware is truly a master piece of it's own. 

My issue: I am under the impression that the input is either inprecise or lagging. I am very often jumping into the spikes or losing sword fights. When attacking  I usually do go forward, raise the sword and hit. So left/right + up+ shift. The up is often  not recognized and I get hit. Does anyone else notice this too, or am I just that bad...

**Comment by berikv** [comment]
I could be wrong, but I that what you are describing is how the game is supposed to work. Like the prince himself, you need to anticipate and prepare the jump before it's too late. Good luck!

**Comment by NagyD** [comment]
@paines, can you verify whether it's specific to SDLPoP or it happens in the original game as well?

**Comment by paines** [comment]
@NagyD unfortunately not. But I think bervik is right. Also I think i need to press harder on the up button to make this work. I will dismiss this as an issue. Thanks to both of you!
