### ISSUE TITLE
Missing variables in savestate

### ISSUE THREAD

**Issue by SergioMartin86** [NagyD/SDLPoP#265]
Hi David,

The following two variables are missing in SDLPoP savestate, as far as I'm concerned. 

is_guard_notice
can_guard_see_kid

Not having this will cause a desync if you save right at this point in level 8:

![image](https://user-images.githubusercontent.com/12969989/144583830-72732a8d-f461-456a-bb2a-ca20d19a527c.png)

In the context of this skip: https://www.youtube.com/watch?v=-xVzTwd7VmA

**Comment by NagyD** [comment]
I added them to the savestate: d7ea0f67bb3c9679119ed7c2b255aef650520ca4

By the way, commit db9068aeefa4bf0b37ab5283ffd11ada4e148bfd tried to work around that can_guard_see_kid is not saved.
