### ISSUE TITLE
Project uses spaces and tabs for indentation

### ISSUE THREAD

**Issue by berikv** [NagyD/SDLPoP#268]
I would suggest to use four spaces, but don't want to start a war over it :)
If tabs are the way to go, then lets convert all spaces to tabs in the remaining .c and .h files.

**Comment by NagyD** [comment]
I changed spaces to tabs where they were used for indentation (as opposed to aligning).
I didn't change the external libraries, though (`src/opl3.c`, `src/opl3.h`, `src/stb_vorbis.c`).

**Comment by berikv** [comment]
How would you feel about moving the external libraries to eg `src/vendor/` and having a formatter / validator script in the project to fix the tabs / spaces?
