### ISSUE TITLE
Can't "careful step" with joysticks not compatible with SDL_GameController

### ISSUE THREAD

**Issue by lorsanta** [NagyD/SDLPoP#273]
I think that the bug is caused by this line:
https://github.com/NagyD/SDLPoP/blob/211796b7a905028b6c1583bb6c78014bfaa385a0/src/seg009.c#L3509
Instead of `joy_X_button_state = -1;` we should have `joy_X_button_state = 1;` as it is done here:
https://github.com/NagyD/SDLPoP/blob/211796b7a905028b6c1583bb6c78014bfaa385a0/src/seg009.c#L3448

**Comment by NagyD** [comment]
Done: ed7246a5b836627a85f61b7e0f5fac1d8ff1870a

You wrote "I think". Can you verify if this change indeed fixes the bug?

**Comment by lorsanta** [comment]
Yes it does, I just double-checked now.
