### ISSUE TITLE
[enhancement] redefine_keyboard2 branch

### ISSUE THREAD

**Issue by cesarpuig** [NagyD/SDLPoP#287]
Hello.

Keyboard settings are not saved once you exit the game. You could add the option to redefine the enter and esc keys, to navigate through the menus.

Thanks a lot

**Comment by NagyD** [comment]
> Keyboard settings are not saved once you exit the game. 

I have added code to save them into the SDLPoP.cfg: 0ba7ebdb9eeb138c22763e5b5386613a2da3c73f

> You could add the option to redefine the enter and esc keys, to navigate through the menus.

Done: 9aab113bb04c571d91991b9f142f822e62f033f5

**Comment by cesarpuig** [comment]
@NagyD


Thank you very much, it works perfectly
