### ISSUE TITLE
compiling error

### ISSUE THREAD

**Issue by grandpa1946** [NagyD/SDLPoP#295]
when i run the build.bat script, it says 
fatal error C1083 could not find sdl.h
anyone knows why and how to fix this? i use visual studio community 2022. in build.bat is no trace of sdl.h, so i don't know how it can get that error.

**Comment by grandpa1946** [comment]
i've tried to recompile a few times, but i keep getting that error

**Comment by NagyD** [comment]
> fatal error C1083 could not find sdl.h

I assume you have set the `SDL2` environment variable as [explained in the Readme](https://github.com/NagyD/SDLPoP#visual-studio).
Does `SDL.h` exist at `%SDL2%\include\SDL.h`?

> in build.bat is no trace of sdl.h, so i don't know how it can get that error.

`SDL.h` is included from `types.h`, which is included from `common.h`, which is included from most `*.c` files, which are directly referenced from `build.bat`.

**Comment by grandpa1946** [comment]
i used the default download (code) so no.

**Comment by NagyD** [comment]
For Visual Studio you need the `*-VC.zip` files from:
* https://github.com/libsdl-org/SDL/releases/latest
* https://github.com/libsdl-org/SDL_image/releases/latest

**Comment by grandpa1946** [comment]
thx
