### ISSUE TITLE
Mobile Port (ask)

### ISSUE THREAD

**Issue by dantedevo** [NagyD/SDLPoP#302]
Hello, I would like to ask a question, I don't know if it is very complicated to make a port for android (and if it is possible in iOS) I just want to ask the question of whether it can be done? I don't want to bother, I'm just asking if it could be done, i can play it on my pc but i would like to play it when i'm not at home.

**Comment by adolfogp** [comment]
Have you tried the web version at https://princejs.com/ ?

It can work in full-screen mode by opening the three dots menu and selecting "Add to Home screen".

**Comment by dantedevo** [comment]
oh thanks I hadn't seen it
