### ISSUE TITLE
Build failure on Fedora Linux

### ISSUE THREAD

**Issue by mattiaverga** [NagyD/SDLPoP#309]
I'm trying to build SDLPoP on Fedora, but I get build failures due to some `implicit-function-declaration` errors:
```
/builddir/build/BUILD/SDLPoP-1.23/src/seg009.c:2138:46: error: implicit declaration of function â€˜strdupâ€™; did you mean â€˜strcmpâ€™? [-Werror=implicit-function-declaration]
 2138 |                         sound_names[index] = strdup(name);
      |                                              ^~~~~~
      |                                              strcmp
/builddir/build/BUILD/SDLPoP-1.23/src/seg009.c:2138:44: warning: assignment to â€˜char *â€™ from â€˜intâ€™ makes pointer from integer without a cast [-Wint-conversion]
 2138 |                         sound_names[index] = strdup(name);
      |                                            ^
/builddir/build/BUILD/SDLPoP-1.23/src/seg009.c: In function â€˜load_soundâ€™:
/builddir/build/BUILD/SDLPoP-1.23/src/seg009.c:2181:43: error: implicit declaration of function â€˜filenoâ€™; did you mean â€˜d_filenoâ€™? [-Werror=implicit-function-declaration]
 2181 |                                 if (fstat(fileno(fp), &info))
      |                                           ^~~~~~
      |                                           d_fileno
In file included from /builddir/build/BUILD/SDLPoP-1.23/src/seg009.c:21:
/builddir/build/BUILD/SDLPoP-1.23/src/seg009.c: In function â€˜draw_overlayâ€™:
/builddir/build/BUILD/SDLPoP-1.23/src/seg009.c:2628:63: error: implicit declaration of function â€˜strnlenâ€™; did you mean â€˜strlenâ€™? [-Werror=implicit-function-declaration]
 2628 |                         int extra_numeric_chars = MAX(0, (int)strnlen(timer_text, sizeof(timer_text)) - 8);
      |                                                               ^~~~~~~
/builddir/build/BUILD/SDLPoP-1.23/src/common.h:59:24: note: in definition of macro â€˜MAXâ€™
   59 | #define MAX(a,b) ((a)>(b)?(a):(b))
      |                        ^
```
AFAIK both `fileno` and `strnlen` aren't part of standard library.

**Comment by NagyD** [comment]
> AFAIK both `fileno` and `strnlen` aren't part of standard library.

According to the pages below, they should be part of the standard library,
but some feature test macros should be defined before including any headers (in `common.h`).
https://linux.die.net/man/3/fileno
https://linux.die.net/man/3/strnlen
`strdup` needs macros as well:
https://linux.die.net/man/3/strdup

You could try adding these in `common.h`, before the `#include`s:
```c
#define _XOPEN_SOURCE 700
#define _POSIX_SOURCE 200809L
```

However, it might be that these macros are not defined by default *exactly because* your system does not support the features behind them.

**Comment by mattiaverga** [comment]
Thanks, I've managed to build successfully by commenting out
[set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -Wall -std=c99")](https://github.com/NagyD/SDLPoP/blob/bf97796df594688fae6f7b68fbcd57f20a7beb13/src/CMakeLists.txt#L4)
(I suppose the `-std=c99` was wrong).
However, my purpose was to package SDLPoP in Fedora repositories, but I later discovered that the data resources location cannot be configured to be out of the binary directory, so... never mind.
