### ISSUE TITLE
when building and executing, i get error 0xc000007b. using release, not debug

### ISSUE THREAD

**Issue by grandpa1946** [NagyD/SDLPoP#311]

**Comment by NagyD** [comment]
Do you not get this error if you compile in debug mode?

0xC000007B means "invalid image format".
That is, the EXE (or one of the DLLs) is 32-bit but it should be 64-bit, or the other way around.

**Comment by dstarosta** [comment]
The sdl.dll and/or sdl_image.dll is 32-bit instead of 64-bit, or the other way around.

The error does not occur if you debug from dev-cpp because it uses the source code of the libraries.

**Comment by grandpa1946** [comment]
> Do you not get this error if you compile in debug mode?
> 
> 0xC000007B means "invalid image format". That is, the EXE (or one of the DLLs) is 32-bit but it should be 64-bit, or the other way around.
> 
> I found this for the error, I don't know if it helps: [answers.microsoft.com/en-us/windows/forum/all/fix-how-to-fix-the-0xc000007b-error/7ceb6950-306b-441e-994d-a353a14b3bca](https://answers.microsoft.com/en-us/windows/forum/all/fix-how-to-fix-the-0xc000007b-error/7ceb6950-306b-441e-994d-a353a14b3bca)

i was just thinking that! sorry for the "false" error
didn't think about matching the architecture of the exe with the architecture of the dll... thanks!
