### ISSUE TITLE
OSX: inconsistence docs, incomplete cmakelist.txt build file

### ISSUE THREAD

**Issue by mfn** [NagyD/SDLPoP#49]
Hello :-)

I've next to know experience with C on OSX so please bear with me. But once I learned about this project I couldn't resist to build it. Luckily I could figure out how but on the way some inconsistencies popped up:

#### Ports vs. Homebrew
The [Readme.txt](https://github.com/NagyD/SDLPoP/blob/master/doc/Readme.txt) mentiones Ports but I can confirm that Homebrew worked as well for me:
`brew install sdl2 sdl2_image sdl2_mixer`

However it seems `*.ogg` are not supported by this version of mixed, as I'm getting: `Unrecognized sound file type`

Btw, what do you think about moving `/docs/Readme.txt` to `/readme.md`, format it a bit to markdown on the way? I think it would be nicer for first time visitors to have this information here readily presented.

#### Building with cmake
The [CMakeLists.txt](https://github.com/NagyD/SDLPoP/blob/d289c8d2780ff1a11c1808b8af7cd7f572e51ec8/CMakeLists.txt#L50) actually contains a comment that the OSX configuration is missing; I was able to get i working with this change:
```DIFF
diff --git a/CMakeLists.txt b/CMakeLists.txt
index c5f4791..1e36bcf 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -49,7 +49,7 @@ add_executable(prince ${SOURCE_FILES})

 # @Todo: add a configuration for Mac OS X

-target_link_libraries(prince mingw32 SDL2main SDL2 SDL2.dll SDL2_image SDL2_mixer)
+target_link_libraries(prince SDL2main SDL2 SDL2_image SDL2_mixer)


```
#### Building with just make
The Readme.txt mentions to use `make -f Makefile.osx`. However this file does not exist and `Makefile` seems to handle both cases already, as it worked out of the box without any changes but just running `make`.

Not sure I'm trying to make any point here, maybe it's useful for people not having a plan what they're doing :-)

thanks

PS: awesome project, btw!

**Comment by NagyD** [comment]
Hello and welcome!

First, I need to mention that OSX-related things were done by StaticReturn and @ecalot.
And, CMake-related things are done by @Falcury.

> The Readme.txt mentions to use `make -f Makefile.osx`. However this file does not exist and Makefile seems to handle both cases already

You're right, the Makefiles were merged in bc3c1c12faa51d39c65806b12efa70c26eefabba without changing the Readme.
I updated it now: f99c42309be7bc1b03cd4fb216de9ec48577afbe

> The CMakeLists.txt actually contains a comment that the OSX configuration is missing; I was able to get i working with this change:

Okay. If possible, you should add an `if` so that Windows sees the original line with `mingw`.

> Btw, what do you think about moving `/docs/Readme.txt` to `/readme.md`, format it a bit to markdown on the way?
> I think it would be nicer for first time visitors to have this information here readily presented.

Markdown is a good idea, but I'm not sure whether the *whole* Readme belongs to the main page.
Anyway, it's a good thing if people see that this project is alive.

Thanks for your comments!
Feel free to make a pull request for anything you mentioned.

**Comment by ecalot** [comment]
My mistake, I forgot to remove the -f argument in the documentation!

**Comment by mfn** [comment]
Ok, thanks for the feedback! :)

Btw, being a complete n00b to the whole OSX/brew thing is already shown why I don't had ogg support: it's a matter of running `brew install sdl2_mixer --with-libvorbis` actually.

**Comment by ecalot** [comment]
I've pull requested your suggestions to the readme file

**Comment by Falcury** [comment]
I added a pull request for the CMake configuration, with an `if` so that on Windows `mingw32` and `SDL2.dll` will still be linked.

**Comment by NagyD** [comment]
Can we close this now, or is there still something left?

**Comment by mfn** [comment]
I don't have time right to now to verify the issues but IMHO it's fine to close it and if I find something at a later point I would open another issue!

**Comment by NagyD** [comment]
Okay.
