### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by akien-mga** [NagyD/SDLPoP#6]
Hi,

Please add a license to your repository, in the current state it's not "open source" as claimed by the description, since there is no licensing information to specify under which terms the code can be reused.

See http://choosealicense.com

**Comment by NagyD** [comment]
Added GPLv3 license: e4a2ce86611c440146df500209af5e946d2cd8b2

**Comment by myself600** [comment]
Thanks for choosing a free (as in freedom) software license! :heart:
