### ISSUE TITLE
Poor sound quality

### ISSUE THREAD

**Issue by myself600** [NagyD/SDLPoP#60]
By default, SDLPoP outputs audio in 22050Hz / 8-bit / Mono which results in a dull and noisy background music. I was able to double the sampling rate and the number of channels, but increasing the bit-depth garbles the sound effects, resulting in an unpleasant high-pitched sound (this is likely because they're stored in a 8-bit format). I've tried to use different output formats (including `AUDIO_S16SYS` as suggested [here](http://sdl.beuc.net/sdl.wiki/Mix_OpenAudio)), but I'm unable to fix this.

**Comment by NagyD** [comment]
> I was able to double the sampling rate and the number of channels,

I don't think that the number of channels makes any difference, since all sounds are mono.

> but increasing the bit-depth garbles the sound effects, resulting in an unpleasant high-pitched sound

This occurs only with SDL 2.0.3 but not with 2.0.4. (And only after doubling the sampling rate.)
It's probably this SDL bug: http://forum.princed.org/viewtopic.php?p=14373#p14373

As for the original problem:
It seems to be enough to increase the number after `desired->samples`.

**Comment by myself600** [comment]
> I don't think that the number of channels makes any difference, since all sounds are mono.

Yes, if using the original Adlib synth. But I also use alternative recordings, including a [live performance](https://www.youtube.com/watch?v=Cda9C5tmom8) which is stereophonic.

> This occurs only with SDL 2.0.3 but not with 2.0.4. (And only after doubling the sampling rate.)
It's probably this SDL bug: http://forum.princed.org/viewtopic.php?p=14373#p14373

> As for the original problem:
It seems to be enough to increase the number after desired->samples.

Thanks! Upgrading SDL to 2.0.4 solved the problem. Btw., is `AUDIO_S16` sufficient to use, or should I use something different (like `AUDIO_S16SYS`)?

As for the latter, increasing the samples doesn't have any effect.

**Comment by myself600** [comment]
Sadly, upgrading to SDL 2.0.4 also breaks the colors.

![screenshot from 2016-03-26 21 37 48](https://cloud.githubusercontent.com/assets/3542623/14062323/25b315fa-f39b-11e5-95e2-cb2344cb65c7.png)

**Comment by myself600** [comment]
I was able to fix the aforementioned issue by reversing your [changeset 9688](https://hg.libsdl.org/SDL/rev/596a3da0c9cb). I've also tried to apply the patch you suggested against SDL 2.0.3, but the audio issue is still present. I'm attaching the patched binaries for you to try (use `prince.sh` to run the game).

:paperclip: [sdlpop-1.16_audio_fix.zip](https://github.com/NagyD/SDLPoP/files/190787/sdlpop-1.16_audio_fix.zip)

**Comment by NagyD** [comment]
> Sadly, upgrading to SDL 2.0.4 also breaks the colors. :disappointed:

I made the RGB swap conditional here: 0fd40c9d58a048ef348a755702deee134810a751
Are you not using the latest SDLPoP sources?

> Thanks! Upgrading SDL to 2.0.4 solved the problem. Btw., is `AUDIO_S16` sufficient to use, or should I use something different (like `AUDIO_S16SYS`)?

According to [the docs](http://wiki.libsdl.org/SDL_AudioFormat), the only difference is the byte order:
`AUDIO_S16` = little-endian, `AUDIO_S16SYS` = system's byte order.
[SDLPoP does not (yet) support non-little-endian systems](https://github.com/NagyD/SDLPoP/blob/master/types.h#L30) anyway, because there was no demand for it.

> But I also use alternative recordings, including a live performance which is stereophonic.

Oh, okay then, I didn't know about that.

**Comment by myself600** [comment]
> I made the RGB swap conditional here: 0fd40c9
Are you not using the latest SDLPoP sources?

I started modding the v1.16 release from princed.org; now I've switched to the `master` branch. Thanks for noting that. (problem solved)

> According to the docs, the only difference is the byte order:
AUDIO_S16 = little-endian, AUDIO_S16SYS = system's byte order.
SDLPoP does not (yet) support non-little-endian systems anyway, because there was no demand for it.

I read that too, and noticed that other projects uses `AUDIO_S16SYS` instead. I ended up using `AUDIO_S16` as it works without issues.

> Oh, okay then, I didn't know about that.

My point is that it's not a good idea to impose restrictions on the output quality (moreso if the input is a PCM stream). Using a sampling rate between 44 and 48kHz at 16-bit/Stereo will circumvent this.

I also noticed that you've tried to fix (in 73ed338) the audible noise by raising the size of audio buffer. However, the problem is caused by the audio bit depth as that's what is responsible for the signal-to-noise ratio. Changing the value of `desired->format` to `AUDIO_S16` (and including a newer SDL library in future releases) will fix this.

This issue can be closed as the bug is with SDL, and not SDLPoP.

**Comment by NagyD** [comment]
> I also noticed that you've tried to fix (in 73ed338) the audible noise by raising the size of audio buffer.
> However, the problem is caused by the audio bit depth as that's what is responsible for the signal-to-noise ratio.

Maybe we are having different problems?
My problem was more like lagging or skipping, and it was solved by this change.
If I increase the samplerate, the format, and the channels (as you did), then even 512 is too small and I need 1024.

Here is what I did now: ba1fd9d58f5e8ee62f14a8939669cb0094cf6c7a

> (and including a newer SDL library in future releases)

Yes, but SDL 2.0.4 has a new bug instead: http://forum.princed.org/viewtopic.php?p=18142#p18142
Looks like I have to recompile SDL for myself if I want a bug-free version...

> This issue can be closed as the bug is with SDL, and not SDLPoP.

Right.

**Comment by myself600** [comment]
> My problem was more like lagging or skipping, and it was solved by this change.

You mean audio clipping? Yes, raising the buffer size should solve this.

> If I increase the samplerate, the format, and the channels (as you did), then even 512 is too small and I need 1024.

Interestingly, this doesn't apply to me (the audio works without clipping, in CDDA quality, even with `desired->samples` set to 256).

> Here is what I did now: ba1fd9d

Any reason why you used `AUDIO_U16SYS` as `desired->format`? I'm just curious since `AUDIO_S16` works perfectly fine to me.

> Yes, but SDL 2.0.4 has a new bug instead: http://forum.princed.org/viewtopic.php?p=18142#p18142
Looks like I have to recompile SDL for myself if I want a bug-free version...

I don't have this issue (**I can** resize the window as well as switch to/exit fullscreen on my Trisquel 7.0 64-bit operating system). Probably an OS-specific bug.

What about solving this problem upstream, then including a self-compiled library made from the development tree?

As for the GNU/Linux executable, you can include the generic _libSDL2-2.0.so.0_ file (you can [download it from Arch packages](https://www.archlinux.org/packages/extra/x86_64/sdl2/download/)) with a small shell script that will use the local library in place of the system-wide one. If you don't get what I mean, take a look inside _building-sdlpop-dev.wiki_ in the link I've provided in [my other report](https://github.com/NagyD/SDLPoP/issues/61#issuecomment-202881550).

**Comment by NagyD** [comment]
> Probably an OS-specific bug.

Exactly, it occurs [only with Direct3D 9 under Windows](http://forum.princed.org/viewtopic.php?p=18149#p18149).

> What about solving this problem upstream,

Do you mean in the SDL Mercurial?
[The next post](http://forum.princed.org/viewtopic.php?p=18143#p18143) has a [patch](https://bugzilla.libsdl.org/attachment.cgi?id=2364&action=edit).
[The current version on Mercurial](https://hg.libsdl.org/SDL/file/fe9cf7c678f4/src/render/direct3d/SDL_render_d3d.c#l1001) does not have the patch applied yet, though.
Anyway, I can apply it myself then.

**Comment by myself600** [comment]
Just noting that it might be a good idea to also include in README that you're using a patched version of SDL along with the link to the bug report/patch.
