### ISSUE TITLE
Doubling the resolution for modding purposes

### ISSUE THREAD

**Issue by myself600** [NagyD/SDLPoP#61]
My other problem is mostly unrelated to the SDLPoP development. I'm trying to improve the graphics by replacing the low resolution sprites with the ones from the 1992 Macintosh version. I was able to do this with the titles, however, I have stumbled upon a deal-breaking issue. The coordinates defining the placement of the objects on the screen are bound by the 8-bit integrer limit (precisely 255 pixels; higher values result in a integrer overflow) meaning that I cannot place them where they belong.

![the_floating_duo](https://cloud.githubusercontent.com/assets/3542623/14029417/4de7ade6-f202-11e5-8b6d-900c6d9c75a4.png)
_The floating duo… I can't get them back to floor. Jaffar is visible too._

Unfortunatelly, I'm not a programmer so I cannot figure out how to fix this.

**Comment by NagyD** [comment]
It should be enough to double the coordinates directly before drawing.
That is, in the `method_*` functions or maybe in `rect_to_sdlrect`.
(I didn't try this yet.)

**Comment by myself600** [comment]
Unfortunately, I have no idea how to do this. :confused:

**Comment by NagyD** [comment]
I started to do that yesterday, now I only need to test it with the bigger images.

**Comment by NagyD** [comment]
Here is what I have now: http://forum.princed.org/viewtopic.php?f=126&t=3810

**Comment by myself600** [comment]
> I started to do that yesterday, now I only need to test it with the bigger images.

A little late but I've cleaned up my work so you don't have to do everything from scratch. You can access it by navigating to

_http://tep.shoutwiki.com → wiki source (left sidebar) → development/**sdlpop**_

in _SDLPoPHD.7z_. This is a very early work-in-progress stuff, and currently only the first two screens are showing properly. The rest of the folder should be stable.

> Here is what I have now: http://forum.princed.org/viewtopic.php?f=126&t=3810

I have to take a better look at this. I'm worried though since doubling the size of coordinates will not allow per-pixel precision, and I doesn't want to compensate that on the sprites. My goal is to improve the original PC version using SDLPoP and the sprites from the Mac version, not to convert SDLPoP to the Mac version.

**Comment by NagyD** [comment]
> currently only the first two screens are showing properly

Yes, anything else will crash the game.
This might be useful: ba7b9f12e0fd4136ebf336345a62ecc254ccbbe3 (Don't crash if some (or all) data files are missing.)

> My goal is to improve the original PC version using SDLPoP and the sprites from the Mac version, not to convert SDLPoP to the Mac version.

Ummm... Yeah, maybe I should have used the DOS images resized to 2x instead?

> I'm worried though since doubling the size of coordinates will not allow per-pixel precision

Yes, for example the two halves of the skeleton don't quite match in position...

However, if all images had even sizes, then this probably would not be a problem.

**Comment by myself600** [comment]
> Yes, anything else will crash the game.

It shouldn't (unless you try to play the game, which isn't going to work anyway). The linked archive contains symlinks to SDLPoP data (_data/music_adlib_, _data/music_live_, _DIGISND*.DAT_, _GUARD1.DAT_, _GUARD2.DAT_ & _LEVELS.DAT_) instead, that's why it's crashing. You have to include those files beforehand, and also rename _music_live_ to _music_ if your operating system doesn't support symbolic links.

> Ummm... Yeah, maybe I should have used the DOS images resized to 2x instead?

The archive already has those images upscaled so you can test your changes right away.

> However, if all images had even sizes, then this probably would not be a problem.

As I said, it's a problem because it prevents precise work (e.g. the stars in the window of the princess's room can't be one pixel wide, etc.). What I meant to ask was if it's possible to use some in-place hack to raise the integrer limitation to 16-bit (i.e. set `Char.x` or `Char.y` to >= 256). Again, I'm not a programmer so I don't know how to do this.

**Comment by NagyD** [comment]
> What I meant to ask was if it's possible to use some in-place hack to raise the integrer limitation to 16-bit

Find [`char_type` in `types.h`](https://github.com/NagyD/SDLPoP/blob/master/types.h#L256), and change the type of `x` and `y` to `short` (16-bit) or `int` (32-bit).
But that's not enough...
You also need to change these types: `objtable_type`, `mob_type`, `back_table_type`, `midtable_type`, `wipetable_type`.
And the parameters of these functions: `x_to_xh_and_xl`, `add_midtable`, `add_backtable`, `add_foretable`.
And then of course change `add_table_type` which is a function pointer that could refer to any of the previous `add_*table` functions.

And then you still can't just simply double the x coordinates in `init_princess` and the like, because they use a different coordinate system...
Maybe it's better to change `calc_screen_x_coord` instead.

**Comment by myself600** [comment]
> Maybe it's better to change calc_screen_x_coord instead.

This corrected the placement of characters horizontally. Any idea how to do it also vertically?

**Comment by NagyD** [comment]
Sorry for the late reply.
Add `ypos = 2*ypos + image->h;` into `draw_mid()`, somewhere after `ypos` got its value.

**Comment by myself600** [comment]
> Sorry for the late reply.

I thought you've lost interest. Since I have no C skills, I'm heavily relying upon outside help. At least, you should notify me if you cannot work on this so I know I just have to wait. (good intention here)

> Add ypos = 2*ypos + image->h; into draw_mid(), somewhere after ypos got its value.

This worked like a charm, thanks! Although this solution still limits the values to even numbers only, I intend to use the original PC character sprites so this isn't a problem for me (at least not yet). However, other modders in the future might stumble upon this issue if they would like to use the MAC character sprites, for example. Other solution would be to split the value into two separate variables (like with `princess_torch_pos_xh[]` and `princess_torch_pos_xl[]`). Anyway, I currently don't see a better solution myself.

At least my work remaking the Princess's room wasn't wasted. :relieved:

This issue can be now marked as solved.

**Comment by NagyD** [comment]
> At least, you should notify me if you cannot work on this so I know I just have to wait.

I should have mentioned this earlier:
I have a day-time job, so my free time is limited to weekends. (And maybe the evenings of weekdays.)

> This issue can be now marked as solved.

Done.
