### ISSUE TITLE
Sound problems

### ISSUE THREAD

**Issue by BenWlson** [NagyD/SDLPoP#64]
Since the last couple commits related to sound I've lost sound completely when compiling on my Raspberry Pi and several of the sound effects are now replaced with only static when compiling in Ubuntu on x86.

**Comment by Falcury** [comment]
I think this occurs due a bug in SDL that was fixed in 2.0.4
See the discussion for the sound quality issue: #60 

Perhaps we could make the sound quality fix conditional based on the version information from `SDL_version.h` (maybe something like `!(SDL_MINOR_VERSION == 0 && SDL_PATCHLEVEL <= 3)`)

**Comment by BenWlson** [comment]
I know for certain the SDL2 version on my raspberry pi was reverted to 2.0.3 (I'm using retropie, and they had some reason for this).

I'm not sure the SDL2 version used in Linux Mint 17.3.

**Comment by myself600** [comment]
Like _Falcury_ said, the static noise occurs because of a bug in SDL. A temporary workaround (at least until your operating system ships SDL 2.0.4) is to download ([32-bit](https://www.parabola.nu/packages/extra/i686/sdl2/download/)/[64-bit](https://www.parabola.nu/packages/extra/x86_64/sdl2/download/)) and place _libSDL2-2.0.so.0_ into your SDLPoP folder, and execute `LD_LIBRARY_PATH=. ./prince` from Terminal to run the game.

**Comment by NagyD** [comment]
> Perhaps we could make the sound quality fix conditional based on the version information from `SDL_version.h`
> Disadvantage might be that this would be decided at compile time.

Maybe the code should detect the bug itself instead of the SDL version?
Just like I did with the RGB24 bug: 0fd40c9d58a048ef348a755702deee134810a751

**Comment by myself600** [comment]
Personaly, I think it should be better to just wait until the upstream distributions will catch up. Ubuntu 16.04 LTS is [targeted for a release in April 21](https://en.wikipedia.org/wiki/Ubuntu_%28operating_system%29#Releases) this month and [already provides SDL 2.0.4](http://packages.ubuntu.com/xenial/libsdl2-2.0-0) (Linux Mint 18 should follow [around May/June](https://en.wikipedia.org/wiki/List_of_Linux_Mint_releases#Release_history)), Debian 9 [provides SDL 2.0.4 in testing branch](https://packages.debian.org/stretch/libsdl2-2.0-0), while rolling release distros like Arch [already has](https://www.archlinux.org/packages/?repo=Extra&q=sdl2) the latest SDL available.

As for Windows, the release archives on [princed.org](http://www.princed.org/downloads/#SDLPoP)/[popot.org](http://www.popot.org/get_the_games.php?game=SDLPoP) contains the required libraries so this isn't a problem there.

**Comment by vanfanel** [comment]
I am using SDL 2.0.4 on the Raspberry Pi 1/2 (I build my own libs and I am not depending on RetroPie nor do I have to wait for my distro tu update) , and the latest version is also silent for me on the Raspberry Pi.

**Comment by myself600** [comment]
Well, I've tried to compile the latest code and both the sound effects and intro/cutscene music are working fine for me. You should try to track down the change that causes the problem (likely something from ba1fd9d).

**Comment by vanfanel** [comment]
@myself600 : 
I found the culprit. Changed 
desired->format = AUDIO_U16SYS
to
desired->format = AUDIO_S16;
...and audio works again :+1:

**Comment by NagyD** [comment]
So 16-bit has to be signed?
Done: 0a1e6192dab6cf38046e7d13a861010bd60c91dd

**Comment by vanfanel** [comment]
@NagyD : I suppose so, in other engines I have seen it as signed, like Cannonball, and it works well.

**Comment by myself600** [comment]
This issue is solved for nearly a month, with no further response from the OP. I think it should be closed.

**Comment by BenWlson** [comment]
Yes. My linux PC and Raspberry pi have both been updated to SDL 2.0.4 and the sound now works well.

BTW, I used you port to finally beat POP for the first time. It was a great experience. Job well done, guys!
