### ISSUE TITLE
rebind Quit to something less easy to accidentally press than B button

### ISSUE THREAD

**Issue by JPLeBreton** [NagyD/SDLPoP#68]
For any controller config where B is one of the main face buttons, Quit is too easy to press, resulting in accidental lost progress. Since the button mappings are hardcoded, consider remapping it to another button further from most players' thumb resting position, like Start.
It looks like the code refers to buttons by index, so I'm not sure if there's a consistent index that gets you such a button.

**Comment by NagyD** [comment]
> consider remapping it to another button further from most players' thumb resting position, like Start.

Done: 49a3e26a41dcbda8dca25cbb79b95a2ec1f60807

Note that I don't have a controller (support was added by Norbert (@EndeavourAccuracy) at 01f9e7cca8af2ef44a17b55ef683328181d6b33f), so I can't really test it.
Please tell me whether it works correctly.

> It looks like the code refers to buttons by index, so I'm not sure if there's a consistent index that gets you such a button.

Actually there is at least one user for whom the indexes are messed up: http://forum.princed.org/viewtopic.php?p=18027#p18027

The new Controller API seems to have [consistent button IDs](http://wiki.libsdl.org/SDL_GameControllerButton), so the best solution would be to use that.
I might do that someday.
