### ISSUE TITLE
Too fast toggling full screen on Alt+Enter

### ISSUE THREAD

**Issue by zaps166** [NagyD/SDLPoP#75]
Steps to reproduce: Press Alt+Enter.
Expected result: Toggles once from/to full screen.
Actual result: Toggles many times at maximum speed, so it is very difficult to set the mode properly :smile:

**Comment by NagyD** [comment]
For this to happen, I have to hold the keys for a much longer time than I usually do.
Anyway, I changed it so Alt+Enter won't repeat itself at all: 115e8611a3203bd14fcf09b76e3b7071d3d0fd80

**Comment by zaps166** [comment]
Thanks :)
See PR #78
